export const creatorTableHead = [
  { heading: "Creator ID", field: "userId", styles: "" },
  { heading: "Profile Image", field: "profilePic", styles: "" },
  { heading: "Name", field: "name", styles: "" },
  { heading: "Email", field: "email", styles: "" },
  { heading: "Phone Number", field: "phoneNumber", styles: "" },
  { heading: "Speciality", field: "speciality", styles: "" },
  { heading: "Created At", field: "createdAt", styles: "" },
  { heading: "Actions", field: "actions", styles: "" },
];


export const creators = [
    {
      userId: "CRE001",
      profilePic: "https://placehold.co/100x100?text=John+Doe",
      name: "John Doe",
      email: "johndoe@example.com",
      phoneNumber: "+1 234 567 8901",
      speciality: "Fashion Designer",
      createdAt: "2024-11-01",
    },
    {
      userId: "CRE002",
      profilePic: "https://placehold.co/100x100?text=Jane+Smith",
      name: "Jane Smith",
      email: "janesmith@example.com",
      phoneNumber: "+1 234 567 8902",
      speciality: "Jewelry Maker",
      createdAt: "2024-11-02",
    },
    {
      userId: "CRE003",
      profilePic: "https://placehold.co/100x100?text=Michael+J",
      name: "Michael Johnson",
      email: "michaelj@example.com",
      phoneNumber: "+1 234 567 8903",
      speciality: "Digital Artist",
      createdAt: "2024-11-03",
    },
    {
      userId: "CRE004",
      profilePic: "https://placehold.co/100x100?text=Emily+Davis",
      name: "Emily Davis",
      email: "emilyd@example.com",
      phoneNumber: "+1 234 567 8904",
      speciality: "Footwear Designer",
      createdAt: "2024-11-04",
    },
    {
      userId: "CRE005",
      profilePic: "https://placehold.co/100x100?text=William+Brown",
      name: "William Brown",
      email: "williamb@example.com",
      phoneNumber: "+1 234 567 8905",
      speciality: "Accessories Maker",
      createdAt: "2024-11-05",
    },
    {
      userId: "CRE006",
      profilePic: "https://placehold.co/100x100?text=Sophia+Wilson",
      name: "Sophia Wilson",
      email: "sophiaw@example.com",
      phoneNumber: "+1 234 567 8906",
      speciality: "Pet Products Designer",
      createdAt: "2024-11-06",
    },
    {
      userId: "CRE007",
      profilePic: "https://placehold.co/100x100?text=James+Taylor",
      name: "James Taylor",
      email: "jamest@example.com",
      phoneNumber: "+1 234 567 8907",
      speciality: "Home Decor Specialist",
      createdAt: "2024-11-07",
    },
    {
      userId: "CRE008",
      profilePic: "https://placehold.co/100x100?text=Olivia+Anderson",
      name: "Olivia Anderson",
      email: "oliviaa@example.com",
      phoneNumber: "+1 234 567 8908",
      speciality: "Model Creator",
      createdAt: "2024-11-08",
    },
  ];
  