export const nonVerifiedCreatorTableHead = [
  { heading: "Name", field: "name", styles: "" },
  { heading: "Email", field: "email", styles: "" },
  { heading: "Phone Number", field: "phoneNumber", styles: "" },
  { heading: "Speciality", field: "speciality", styles: "" },
  { heading: "Verification ID", field: "verificationId", styles: "" },
  { heading: "Created At", field: "createdAt", styles: "" },
  { heading: "Actions", field: "actions", styles: "" },
];

export const nonVerifiedCreators = [
  {
    name: "John Doe",
    email: "johndoe@example.com",
    phoneNumber: "+1 234 567 8901",
    speciality: "Fashion Designer",
    verificationId: "VER123456",
    createdAt: "2024-11-15",
  },
  {
    name: "Jane Smith",
    email: "janesmith@example.com",
    speciality: "Jewelry Maker",
    phoneNumber: "+1 234 567 8902",
    verificationId: "VER123457",
    createdAt: "2024-11-16",
  },
  {
    name: "Michael Johnson",
    email: "michaelj@example.com",
    speciality: "Digital Artist",
    phoneNumber: "+1 234 567 8903",
    verificationId: "VER123458",
    createdAt: "2024-11-17",
  },
  {
    name: "Emily Davis",
    email: "emilyd@example.com",
    speciality: "Footwear Designer",
    phoneNumber: "+1 234 567 8904",
    verificationId: "VER123459",
    createdAt: "2024-11-18",
  },
  {
    name: "William Brown",
    email: "williamb@example.com",
    speciality: "Accessories Maker",
    phoneNumber: "+1 234 567 8905",
    verificationId: "VER123460",
    createdAt: "2024-11-19",
  },
  {
    name: "Sophia Wilson",
    email: "sophiaw@example.com",
    speciality: "Pet Products Designer",
    phoneNumber: "+1 234 567 8906",
    verificationId: "VER123461",
    createdAt: "2024-11-20",
  },
  {
    name: "James Taylor",
    email: "jamest@example.com",
    speciality: "Home Decor Specialist",
    phoneNumber: "+1 234 567 8907",
    verificationId: "VER123462",
    createdAt: "2024-11-21",
  },
  {
    name: "Olivia Anderson",
    email: "oliviaa@example.com",
    speciality: "Model Creator",
    phoneNumber: "+1 234 567 8908",
    verificationId: "VER123463",
    createdAt: "2024-11-22",
  },
];
